# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLqr5AJ007rIvJsaJlZ_a5tfT_yn8vsA
"""

# ============================================================
# 🎤 Voice-to-Text + 🖼️ AI Image Generation (CLEAN VERSION)
# ============================================================

!apt install ffmpeg -y
!pip install livekit-api openai-whisper gradio requests Pillow

import whisper
from livekit import api
import gradio as gr
import requests
from PIL import Image
from io import BytesIO

# ─── CREDENTIALS ─────────────────────────────────────────────
LIVEKIT_URL        = "https://genai-mq7kpfih.livekit.cloud"
LIVEKIT_API_KEY    = "APIVZJeW43TvC4Q"
LIVEKIT_API_SECRET = "w2WWueQHqYu3xlbTwdjpuhzst0tf55zWtwtV8bHTq3A"
HF_API_KEY         = "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"

# ─── LIVEKIT CONNECTION TEST ──────────────────────────────────
async def test_livekit():
    client = api.LiveKitAPI(LIVEKIT_URL, api_key=LIVEKIT_API_KEY, api_secret=LIVEKIT_API_SECRET)
    rooms = await client.room.list_rooms(api.ListRoomsRequest())
    print("✅ LiveKit connected!")
    await client.aclose()

await test_livekit()

# ─── LOAD WHISPER MODEL ───────────────────────────────────────
print("⏳ Loading Whisper model... please wait...")
model = whisper.load_model("base")
print("✅ Whisper model loaded!")

# ─── IMAGE GENERATION ─────────────────────────────────────────
def generate_image(prompt):
    API_URL = "https://router.huggingface.co/hf-inference/models/stabilityai/stable-diffusion-xl-base-1.0"
    headers = {
        "Authorization": f"Bearer {HF_API_KEY}",
        "Content-Type": "application/json"
    }
    response = requests.post(
        API_URL,
        headers=headers,
        json={"inputs": prompt},
        timeout=60
    )
    if response.status_code == 200:
        return Image.open(BytesIO(response.content))
    elif response.status_code == 503:
        raise Exception("⏳ Model is loading. Wait 30 seconds and try again.")
    else:
        raise Exception(f"❌ Image Error {response.status_code}: {response.text}")

# ─── MAIN PIPELINE ────────────────────────────────────────────
def voice_to_image(audio_file):
    # Step 1: Check audio
    if audio_file is None:
        return "⚠️ Please record your voice first!", None

    # Step 2: Transcribe with Whisper
    try:
        print(f"🎵 Transcribing audio...")
        result = model.transcribe(str(audio_file))
        transcription = result["text"].strip()
        print(f"📝 You said: {transcription}")
        if not transcription:
            return "⚠️ No speech detected. Please try again.", None
    except Exception as e:
        return f"❌ Transcription Error: {str(e)}", None

    # Step 3: Generate image
    try:
        print(f"🎨 Generating image for: {transcription}")
        image = generate_image(transcription)
        print("✅ Image generated!")
        return f"🗣️ You said: {transcription}", image
    except Exception as e:
        return f"🗣️ You said: {transcription}\n\n{str(e)}", None

# ─── GRADIO UI ─────────────────────────────────────────────────
with gr.Blocks(title="Voice to Image", theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # 🎤 Voice → Text → 🖼️ AI Image Generator
    ### Speak anything — watch it turn into an AI image!
    **How to use:** Record voice → Click Generate → See your image!
    """)

    with gr.Row():
        with gr.Column():
            audio_input = gr.Audio(
                sources=["microphone"],
                type="filepath",
                label="🎙️ Step 1: Record Your Voice"
            )
            generate_btn = gr.Button(
                "🚀 Step 2: Generate My Image!",
                variant="primary",
                size="lg"
            )

        with gr.Column():
            text_output = gr.Textbox(
                label="📝 What AI heard you say",
                placeholder="Your words will appear here...",
                lines=3
            )
            image_output = gr.Image(
                label="🖼️ Your AI Generated Image",
                type="pil"
            )

    gr.Markdown("""
    ---
    ### 💡 Say these for amazing images:
    - 🌅 *"a beautiful sunset over mountains with a river"*
    - 🐉 *"a dragon flying over a castle at night"*
    - 🤖 *"a robot eating pizza in a restaurant"*
    - 🌊 *"a pirate ship on stormy ocean waves"*
    - 🏙️ *"a futuristic city with flying cars, digital art"*
    """)

    generate_btn.click(
        fn=voice_to_image,
        inputs=[audio_input],
        outputs=[text_output, image_output]
    )

demo.launch(share=True)